// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJPjNsJb9nBiU6UfzfOSmHRN_P-8ei2x0',
    appId: '1:745458362769:web:6f4e7d74521d5860b29230',
    messagingSenderId: '745458362769',
    projectId: 'todolist-4b27e',
    authDomain: 'todolist-4b27e.firebaseapp.com',
    storageBucket: 'todolist-4b27e.appspot.com',
    measurementId: 'G-0N1GNEH5CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1tXApp7l55B6MRuAImAtvIEEAmJnM_Gc',
    appId: '1:745458362769:android:e8b2fa2ad6ca9f30b29230',
    messagingSenderId: '745458362769',
    projectId: 'todolist-4b27e',
    storageBucket: 'todolist-4b27e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXeBTCxsL-DAR2axejpcIHQxjC0OiDIp0',
    appId: '1:745458362769:ios:f57021bde37a9d7cb29230',
    messagingSenderId: '745458362769',
    projectId: 'todolist-4b27e',
    storageBucket: 'todolist-4b27e.appspot.com',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXeBTCxsL-DAR2axejpcIHQxjC0OiDIp0',
    appId: '1:745458362769:ios:c589645bbb103101b29230',
    messagingSenderId: '745458362769',
    projectId: 'todolist-4b27e',
    storageBucket: 'todolist-4b27e.appspot.com',
    iosBundleId: 'com.codeforany.foodDelivery.RunnerTests',
  );
}
